name: Publish Docs

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 15

    # only run on master
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - name: Prepare Environment
        run: yarn
        env:
          CI: true
      - name: Build
        run: yarn build
        env:
          CI: true
      - name: Generate docs
        run: yarn docs:prepare
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
